### ISSUE TITLE
Firebase App Distribution BUG: missing app ID on GitHub Actions

### ISSUE THREAD

**Issue by PavlosTze** [firebase/firebase-android-sdk#3403]
### [REQUIRED] Step 2: Describe your environment

  * Android Studio version: Android Studio Bumblebee | 2021.1.1
  * Firebase Component: Firebase App Distribution
  * Component version: 3.0.0

### [REQUIRED] Step 3: Describe the problem

Just like this [StackOverFlow issue](https://stackoverflow.com/questions/70838922/firebaseappdistribution-with-github-actions-throwing-error-missing-app-id-eve), I have followed your guide for distributing builds through Firebase, and I also used GitHub actions for that. It was working smoothly for 3-4 months, until I recently upgraded to the 3.0.0 version of Firebase App Distribution.

As soon as I did it, I can no longer push builds through firebase as I get the following error on GitHub:
`* What went wrong:
Execution failed for task ':app:appDistributionRemoteDevDebug'.
> Missing app id. Please check that it was passed in and try again`

The following code on Android Studio's terminal (which is the same code I have in the GitHub action) works properly.
`gradlew :app:assembleRemoteDevDebug :app:appDistributionUploadRemoteDevDebug`
#### Steps to reproduce:

1. Create a GitHub action that distributes a build in firebase
2. You will get the following error `Missing app id. Please check that it was passed in and try again`
3. Running the same code that builds the project and uploads it in the Firebase, in the terminal in Android Studio, gives no error at all.

**Comment by umesh0492** [comment]
Happening the same issue with https://github.com/Triple-T/gradle-play-publisher. I thinks this is some firebase issue only if same is happening with multiple libs

**Comment by argzdev** [comment]
Hi @PavlosTze & @umesh0492, thanks for reporting. I'm unable to reproduce this issue on my own repo. Could you check what I'm missing?

GitHub Actions:
```
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@937999e9cc2425eddc7fd62d1053baf041147db7
      with:
        arguments: build
    - name: Upload with Release 
      run: |
        export FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }}
        ./gradlew :app:assembleDemoRelease :app:appDistributionUploadDemoRelease      
```

module build.gradle:
```
android {
...
    buildTypes {
        debug {
            firebaseAppDistribution {
                artifactType="APK"
            }
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            firebaseAppDistribution {
                artifactType="APK"
            }
        }
    }

    flavorDimensions "version"
    productFlavors {
        demo {
            dimension "version"
            firebaseAppDistribution {
                releaseNotes="Release notes for demo version"
            }
        }
        full {
            dimension "version"
            firebaseAppDistribution {
                releaseNotes="Release notes for full version"
            }
        }
    }
...
}
```

project build.gradle:
```
dependencies {
        classpath "com.android.tools.build:gradle:7.0.1"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10"
        classpath 'com.google.firebase:firebase-appdistribution-gradle:3.0.0'
        classpath 'com.google.gms:google-services:4.3.10'
    }
```

Thanks!
