### ISSUE TITLE
Firebase Crashlytics: failed for task ': app:uploadCrashlyticsMappingFileProdRelease'

### ISSUE THREAD

**Issue by annchar** [firebase/firebase-android-sdk#4585]
![Screenshot 2566-01-24 at 16 29 23](https://user-images.githubusercontent.com/6577999/214256338-661c15c7-e9d2-4b02-8ad7-bb68b4a5197f.png)

Hello, I tried to call task `: app:uploadCrashlyticsMappingFileProdRelease` but it was failing I don't know why I ran on another environment it was okay(setup same way). The root cause that I found it doesn't see the file. What should I do?

![Screenshot 2566-01-24 at 16 42 52](https://user-images.githubusercontent.com/6577999/214259600-b347e48f-6da9-4350-99ed-c6b05c748b75.png)
This Folder has been added to .gitignore because of the security policy in my company.

build.gradle.kts
```
plugins {
   ...
    id("com.google.firebase.crashlytics")
}
android {
   ...
   buildTypes {
        named("release") {
            isShrinkResources = true
            isMinifyEnabled = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        named("debug") {
            isMinifyEnabled = false
            isTestCoverageEnabled = true
        }
    }
}
project.afterEvaluate {
    tasks.named("uploadCrashlyticsMappingFileProdRelease") {
        val myDirProp: DirectoryProperty =
            project.objects.directoryProperty().fileValue(file("crashlytics-res/google-services/prod/release"))
        setProperty("googleServicesResourceRoot", myDirProp)
    }
}
```

I use Firebase Crashlytics version is 18.0.1
and plugin version is 2.8.1

My workflow
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.3'

      - name: Install Fastlane
        run: bundle install

      - name: Create service credential file
        env:
          ...
          CRASHLYTICS_CREDENTIALS: ${{ secrets.CRASHLYTICS_CREDENTIALS_PROD }}
        run: |
          ...
          mkdir -p ./app/crashlytics-res/google-services/prod/release/values
          echo "$CRASHLYTICS_CREDENTIALS" > ./app/crashlytics-res/google-services/prod/release/values/values.xml

      - name: Prepare keystore
        ...

      - name: Setup SSH key
        uses: shimataro/ssh-key-action@v2
        ...

      - name: Setup SSH known hosts
        ...

      - name: Deploy PROD on Play Store
        run: |
          bundle exec fastlane deploy_prod_playstore
        env:
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
          ...
```
